language: node_js
before_install:
  - sudo apt-get update
  - sudo curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo apt-get install -y build-essential
install:
  - npm install
script:
  - npm test
deploy:
  provider: script
  - npm run natives
  skip_cleanup: true
  on:
    tags: true
